create table booking (
    end_time timestamp(6) with time zone,
    id bigint generated by default as identity,
    room_id bigint, start_time timestamp(6) with time zone,
    user_id bigint,
    booking_status varchar(50),
    primary key (id)
    );

create table equipments (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    name varchar(255),
    primary key (id)
    );

create table room_equipment (
    equipment_id bigint not null,
    room_id bigint not null
    );

create table rooms (
    capacity integer not null,
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    name varchar(255),
    status varchar(50),
    primary key (id)
    );

create table users (
    created_at timestamp(6) with time zone,
    id bigint generated by default as identity,
    updated_at timestamp(6) with time zone,
    email varchar(255),
    password varchar(255),
    username varchar(255),
    role varchar(50),
    count_reservation integer default 0 not null,
    primary key (id));

alter table if exists booking add constraint FKb6jhn9s6v53eb2cd9l7uhcd0m foreign key (room_id) references rooms;

alter table if exists booking add constraint FK7udbel7q86k041591kj6lfmvw foreign key (user_id) references users;

alter table if exists room_equipment add constraint FKlfrt4lsuppwxcbd47sp7v63ps foreign key (equipment_id) references equipments;

alter table if exists room_equipment add constraint FKiyhaivc7it7c8go6ursatnvte foreign key (room_id) references rooms;

insert into users(username, email, password, role)
values (
           'admin',
           'admin@admin.com',
           '$2a$12$VHynQfbswANiJ0EOsoLFQ.Mwn2MvwIwGPD8gsEWU96RCSAmcwt1qS',
           'ADMIN'
       );

insert into rooms(name, capacity, status)
values (
           'Room 1',
           10,
           'AVAILABLE'
       );